CREATE DATABASE IF NOT EXISTS fhdwhotel;

USE fhdwhotel;

CREATE TABLE IF NOT EXISTS address (
	ID INT NOT NULL AUTO_INCREMENT, 
	Street VARCHAR(35) NOT NULL, 
	HouseNumber INT (4) NOT NULL,
	PostalCode VARCHAR(10) NOT NULL, 
	City VARCHAR(20) NOT NULL, 
	PRIMARY KEY(ID)
); 

CREATE TABLE IF NOT EXISTS hotel(
	ID INT NOT NULL AUTO_INCREMENT, 
	Name VARCHAR(20) NOT NULL, 
	AddressID INT NOT NULL, 
	PRIMARY KEY(ID), 
	FOREIGN KEY(AddressID) REFERENCES address(ID)
);

CREATE TABLE IF NOT EXISTS guest(
	ID INT NOT NULL AUTO_INCREMENT, 
	Firstname VARCHAR(20) NOT NULL, 
	Nachname VARCHAR(20) NOT NULL, 
	Emailaddress VARCHAR(50) UNIQUE NOT NULL, 
	Birthplace VARCHAR(20), 
	Birthday DateTime NOT NULL, 
	Password VARCHAR(35) NOT NULL, 
	Phonenumber VARCHAR(30), 
	ContactAddressID INT NOT NULL, 
	BillingAddressID INT, 
	PRIMARY KEY(ID), 
	FOREIGN KEY(ContactAddressID) REFERENCES address(ID), 
	FOREIGN KEY(BillingAddressID) REFERENCES address(ID) 
);

CREATE TABLE IF NOT EXISTS booking(
	ID INT NOT NULL AUTO_INCREMENT, 
	Arrival DateTime NOT NULL, 
	Depature DateTime NOT NULL, 
	HotelID INT NOT NULL, 
	GuestID INT NOT NULL, 
	PRIMARY KEY(ID),
	FOREIGN KEY(HotelID) REFERENCES hotel(ID), 
	FOREIGN KEY(GuestID) REFERENCES guest(ID)
);

CREATE TABLE IF NOT EXISTS roomcategory(
	ID INT NOT NULL AUTO_INCREMENT, 
	Category VARCHAR(10) NOT NULL, 
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS roomtype(
	ID INT NOT NULL AUTO_INCREMENT, 
	Type VARCHAR(10) NOT NULL, 
	PersonCount INT(2) NOT NULL, 
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS room(
	ID INT NOT NULL AUTO_INCREMENT, 
	RoomNumber varchar(5) NOT NULL, 
	Price Decimal(5,2) NOT NULL, 
	HotelID INT NOT NULL, 
	TypeID INT NOT NULL,  
	CategoryID INT NOT NULL, 
	PRIMARY KEY(ID), 
	FOREIGN KEY(HotelID) REFERENCES hotel(ID), 
	FOREIGN KEY(TypeID) REFERENCES roomtype(ID),
	FOREIGN KEY(CategoryID) REFERENCES roomcategory(ID) 
);

CREATE TABLE IF NOT EXISTS bookingroom(
	ID INT NOT NULL AUTO_INCREMENT,
	BookingID INT NOT NULL,
	RoomID INT NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(BookingID) REFERENCES booking(ID), 
	FOREIGN KEY(RoomID) REFERENCES room(ID)
); 
 
CREATE TABLE IF NOT EXISTS admin(
	ID INT NOT NULL AUTO_INCREMENT,
	Username VARCHAR(25) NOT NULL,
	Passwort VARCHAR(25) NOT NULL,
    PRIMARY KEY(ID)
);
